remote_theme: just-the-docs/just-the-docs
title: Tekstil-MFA Norge
description: Dynamisk, probabilistisk materialstrømanalyse av tekstiler i Norge 1988–2025
nav_sort: case_insensitive
nav_exclude:
  - /index.md
include:
  - output_files
exclude:
  - data_files
  - litteratur
  - tests
  - "*.csv.gz"
